<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAwAr8JL\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAwAr8JL/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAwAr8JL.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAwAr8JL\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerAwAr8JL\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'AwAr8JL',
    'container.build_id' => '92cdba78',
    'container.build_time' => 1622728620,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAwAr8JL');
