<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerI76Eepf\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerI76Eepf/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerI76Eepf.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerI76Eepf\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerI76Eepf\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'I76Eepf',
    'container.build_id' => '37837a3f',
    'container.build_time' => 1622720406,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerI76Eepf');
